
export const items = [
    {
        id: 1,
        name: 'Slim Flex Fit Jean',
        price: 59.90,
        description: 'Washed slim fit jeans with just the right amount of stretch for comfort and flexibility. Front zip and button closure.',
        imagePath1: '/assets/images/1-1.png',
        imagePath2: '/assets/images/1-2.png',
        imagePath3: '/assets/images/1-1.png',
        color: 'Blue',
        amtInStock: 22,
        gender: 'men',
    },
    {
        id: 2,
        name: 'Short-Sleeve Icon Crew Tee',
        price: 25.00,
        description: 'The short-sleeve that keeps you fresh, with a simple profile that completes any outfit.',
        imagePath1: '/assets/images/2-1.png',
        imagePath2: '/assets/images/2-2.png',
        imagePath3: '/assets/images/2-1.png',
        color: 'Black',
        amtInStock: 0,
        gender: 'men',
    },
    {
        id: 3, 
        name: 'Wool Cardigan',
        price: 49.99,
        description: 'Boxy cardigan in a soft knit with wool content. Low-cut V-neck, rhinestone-decorated buttons at front, dropped shoulders, and long sleeves.',
        imagePath1: '/assets/images/3-1.png',
        imagePath2: '/assets/images/3-2.png',
        imagePath3: '/assets/images/3-1.png',
        color: 'Brown',
        amtInStock: 34,
        gender: 'women',
    },
    {
        id: 4,
        name: 'Ripped Jeans',
        price: 59.99,
        description: 'Cut with a straight leg, this sleek pair of jeans promises an awesome look. The light wash and unique seam detail always impress.',
        imagePath1: '/assets/images/4-1.png',
        imagePath2: '/assets/images/4-2.png',
        imagePath3: '/assets/images/4-1.png',
        color: 'Light Wash',
        amtInStock: 12, 
        gender: 'women',
    },
    {
        id: 5,
        name: 'Knit Tie',
        price: 25.99,
        description: 'This tie is featured in a classic for a timeless look. Wear it with one of our dress shirts or under suiting.',
        imagePath1: '/assets/images/5-1.png',
        imagePath2: '/assets/images/5-2.png',
        imagePath3: '/assets/images/5-1.png',
        color: 'Black',
        amtInStock: 124, 
        gender: 'men',
    },
    {
        id: 6,
        name: 'Soft Plaid Scarf',
        price: 19.99,
        description: 'A scarf can be worn in so many ways – knotted in various ways around the neck, wrapped around the head, or over the shoulders.',
        imagePath1: '/assets/images/6-1.png',
        imagePath2: '/assets/images/6-2.png',
        imagePath3: '/assets/images/6-1.png',
        color: 'Black',
        amtInStock: 21, 
        gender: 'women',
    },
    {
        id: 7,
        name: 'Brown Chukka Boot',
        price: 69.90,
        description: 'The rugged and resilient matte leather upper was custom created to look great with years of hard wear and minimal care.',
        imagePath1: '/assets/images/7-1.png',
        imagePath2: '/assets/images/7-2.png',
        imagePath3: '/assets/images/7-1.png',
        color: 'Light Brown',
        amtInStock: 3, 
        gender: 'men',
    },
    {
        id: 8,
        name: 'Sam Edelman Rodney Flat',
        price: 59.99,
        description: 'Stroll around town when wearing the Rodney Flat from Sam Edelman. The shiny, faux patent upper will easily pair with anything.',
        imagePath1: '/assets/images/8-1.png',
        imagePath2: '/assets/images/8-2.png',
        imagePath3: '/assets/images/8-1.png',
        color: 'Light Brown',
        amtInStock: 0, 
        gender: 'women',
    },

]